temporary_folder = ""
permanent_folder = ""
move_highlights = false

transcode_highlights = true
transcode_trim = true
transcode_start_time = "00:00:00"
transcode_end_time = "00:00:25"
transcode_size = 25

preserve_original = true
preserve_transcoded = true

discord_share = false
discord_webhook = ""
discord_username = ""
discord_avatar = ""